/* Author: Liao Yajun */
#ifndef INCORPORATEDSMAPF_H
#define INCORPORATEDSMAPF_H

#include <Eigen/Geometry>

/**
  \brief Incorporating the method of dyanimcial system modulation and repulsive vector field to generate reactive
  motion for a robot treated as a control point.
*/
class IncorporateDsmApf{
private:
  ///output velocity which can avoid collide with obstacles
  Eigen::Vector3f raw_velocity;
  ///input the repulsive vector that denotes the direction of away from the obstacles
  Eigen::Vector3f repulsive_vector;
  ///constructing the modulation matrix
  Eigen::Matrix3f modulation_matrix;
  ///direction between repulsive vector and raw command speed, true means the control point is approaching the obstacle surface.
  bool direction_repvector_rawspeed;
  ///the minimum distance between obstacle and control point
  float min_distance;

  /**
      \brief Find out whether the control point is approaching the obstacle or away from it.

      \param [in] rep_vector. Input the reuplsive vector denoted the direction of approaching obstacle surface.
      \param [in] raw_speed. Input the raw speed generated by dynamical system.
      \return [out] direction_repvector_rawspeed.
      time is unlimited. True means the control point is approaching the obstacle surface, in contrast, it is false.
    */
  bool getDirection(Eigen::Vector3f &rep_vector, Eigen::Vector3f &raw_speed_);

public:
  /**
      \brief Construct a object for utilizing the mothod of combining dynamicial system and repulsive vector field.

      \param [in] repulsive_vector_. denotes the direction of away from the obstacles
      \param [in] raw_velocity_. generated by dynamical system.
      \param [in] min_distance_.  minimum distance between obstacle and control point
    */
  IncorporateDsmApf(Eigen::Vector3f &repulsive_vector_, Eigen::Vector3f & raw_velocity_, float & min_distance_);
  /**
      \brief Computing the modulated velocity.

      \param [out].modulated_velocity_out
    */
  void calculateModulatedVelocity(Eigen::Vector3f & modulated_velocity_out);
  /**
      \brief Computing the modulated matrix.

      \param [in].repulsive_vec is the repulsive vector.
    */
  void calculateModulationMatrix(Eigen::Vector3f & repulsive_vec);
  /**
      \brief Calculating the magunitude of the eigen of the modulated matrix.

      \param [in].distance between control point and obstacle surface.
    */
  float calculateMagunitude(float & distance);

  ~IncorporateDsmApf();
};
#endif
